config/routes.rb
CookAid::Application.routes.draw do
  resources :recipes

  root :to => 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  expose(:recipe)
  expose(:recipes) { Recipe.all }


  def create
    if recipe.save
      redirect_to recipes_url, notice: 'Recipe was successfully created.'
    else
       render action: "new"
    end
  end

  def update
    if recipe.update_attributes(params[:recipe])
      redirect_to recipe, notice: 'Recipe was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    recipe.destroy
    redirect_to recipes_url, notice: "Recipe was succesfully deleted"
  end
end

app/views/application/_content.html.haml
.container
  = render "flashes"
  #content
    = yield

app/views/application/_flashes.html.haml
%ul.flash-messages
  - flash.each do |key, value|
    %li.alert{:title => "#{key.to_s.humanize}", :class => "alert-#{key}"}
      %a.close{ :href => '#', 'data-dismiss'=>'alert'}x
      = value

app/views/application/_head.html.haml
%head
  %meta{:charset => "utf-8"}/
  %title
    CookAid
  %meta{ :name => "viewport", :content => "width=device-width,initial-scale=1" }
  = csrf_meta_tags
  / Le HTML5 shim, for IE6-8 support of HTML elements
  /[if lt IE 9]
  = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
  / Le styles
  = stylesheet_link_tag "application"

app/views/application/_header.html.haml
.navbar
  .navbar-inner
    .container
      %a.brand{:href => "/"}CookAid
      %ul.nav
        %li= link_to "Recipes", recipes_path

app/views/layouts/application.html.haml
!!! 5

= render "head"

%body
  = render "header"
  = render "content"

  = javascript_include_tag "application"

app/views/recipes/_form.html.haml
.clearfix
  = f.label :name, "Name", :class => :label
  .input
    = f.text_field :name, :class => 'text_field'
  = f.label :name,"Description", :class => :label
  .input
    = f.text_area :description, :class => 'text_area', 'rows' => 3

.form-actions
  %button.btn-primary{:type => "submit"} Save
  %a.btn{:href => recipes_path} Cancel

app/views/recipes/edit.html.haml
= form_for recipe, :url => recipe_path(recipe), :html => { :class => "edit_recipe", :id => "edit_recipe" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "form", :locals => {:f => f}

app/views/recipes/index.html.haml
%h1 Recipes
%table{:class => "table-striped"}
  %thead
    %tr
      %th ID
      %th Name
      %th Description
      %th Actions
  %tbody
    - recipes.each do |recipe|
      %tr
        %td= recipe.id
        %td= link_to recipe.name, recipe_path(recipe)
        %td= recipe.description
        %td
          %a.btn{:href => recipe_path(recipe)} Show
          %a.warning-button{:href => edit_recipe_path(recipe)} Edit
          %a.delete-button{:href => recipe_path(recipe), 'data-method' => 'delete', 'data-confirm' => "Are you sure?"}

= link_to "New", new_recipe_path, :class => 'btn btn-primary'

app/views/recipes/new.html.haml
= form_for recipe, :url => recipes_path, :html => { :class => :form } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/recipes/show.html.haml
%label{:class => "label"} Name:
%p= recipe.name
%label{:class => "label"} Description:
%p= recipe.description

.form-actions
  %a.btn{:href => recipes_path} Back
  %a.warning-button{:href => edit_recipe_path(recipe)} Edit
  %a.delete-button{:href => recipe_path(recipe), 'data-method' => 'delete', 'data-confirm' => "Are you sure?"}